spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/for_shiro
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.sun.shiro.demo.respository: debug